
import React, { useState } from 'react';
import { Search, Book, Clock, ChevronRight, Hash, FileText, ArrowLeft, CheckCircle2, AlertCircle } from 'lucide-react';
import { KNOWLEDGE_BASE_DATA } from '../constants';
import { SOP } from '../types';

const KnowledgeBase: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedSop, setSelectedSop] = useState<SOP | null>(null);

  const filteredSops = KNOWLEDGE_BASE_DATA.filter(sop => 
    sop.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    sop.category.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleExportWord = () => {
    if (!selectedSop) return;

    // Word XML + HTML content for styling and structure
    const content = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #334155; }
          .header { border-bottom: 2px solid #1e40af; margin-bottom: 20px; padding-bottom: 10px; }
          .title { color: #1e40af; font-size: 24pt; margin: 0; }
          .meta { color: #64748b; font-size: 10pt; text-transform: uppercase; margin-top: 5px; }
          .section-title { color: #1e40af; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-top: 25px; }
          .purpose { font-style: italic; color: #475569; background: #f8fafc; padding: 15px; border-left: 4px solid #3b82f6; }
          .steps { margin-top: 20px; }
          .step-item { margin-bottom: 10px; }
          .escalation-box { background: #fff7ed; border: 1px solid #ffedd5; padding: 15px; margin-top: 30px; border-radius: 8px; }
          .escalation-title { color: #9a3412; font-weight: bold; margin: 0 0 5px 0; font-size: 11pt; text-transform: uppercase; }
          .footer { margin-top: 50px; font-size: 8pt; color: #94a3b8; text-align: center; border-top: 1px solid #f1f5f9; padding-top: 10px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1 class="title">${selectedSop.title}</h1>
          <div class="meta">${selectedSop.category} | Ref: ${selectedSop.id} | Last Updated: ${selectedSop.lastUpdated}</div>
        </div>

        <h3 class="section-title">Purpose</h3>
        <div class="purpose">${selectedSop.purpose || 'Official standard operating procedure for internal IT use.'}</div>

        <h3 class="section-title">Technical Implementation Steps</h3>
        <ol class="steps">
          ${selectedSop.steps.map(step => `<li class="step-item">${step}</li>`).join('')}
        </ol>

        ${selectedSop.escalation ? `
          <div class="escalation-box">
            <div class="escalation-title">Escalation Policy</div>
            <p style="margin: 0;">${selectedSop.escalation}</p>
          </div>
        ` : ''}

        <div class="footer">
          Generated by Tech It Easy Copilot Platform - Official Documentation Support Hub<br/>
          &copy; ${new Date().getFullYear()} IT Support Operations
        </div>
      </body>
      </html>
    `;

    const blob = new Blob(['\ufeff', content], {
      type: 'application/msword'
    });

    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${selectedSop.id.toUpperCase()}_${selectedSop.title.replace(/\s+/g, '_')}.doc`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl mx-auto p-4 lg:p-8 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-12">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 no-print">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Book size={20} className="text-blue-600" />
            <h1 className="text-2xl lg:text-3xl font-bold">Knowledge Base</h1>
          </div>
          <p className="text-slate-500 text-sm">Official IT Standard Operating Procedures</p>
        </div>
        <div className="relative w-full md:w-96">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
          <input 
            type="text" 
            placeholder="Search procedure..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-11 pr-4 py-3 bg-white border border-slate-200 rounded-2xl shadow-sm focus:ring-2 focus:ring-blue-500 outline-none transition-all"
          />
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* SOP List */}
        <div className={`lg:col-span-5 space-y-3 no-print ${selectedSop ? 'hidden lg:block' : 'block'}`}>
          <div className="flex items-center justify-between px-2 mb-2">
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Available Guides ({filteredSops.length})</span>
          </div>
          {filteredSops.map((sop) => (
            <button
              key={sop.id}
              onClick={() => setSelectedSop(sop)}
              className={`w-full text-left p-5 rounded-3xl border transition-all group ${
                selectedSop?.id === sop.id 
                  ? 'bg-blue-600 border-blue-600 text-white shadow-xl shadow-blue-600/20' 
                  : 'bg-white border-slate-100 hover:border-blue-200 hover:bg-slate-50/50 shadow-sm'
              }`}
            >
              <div className="flex items-center justify-between mb-2">
                <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded ${
                  selectedSop?.id === sop.id ? 'bg-blue-500 text-white' : 'bg-slate-100 text-slate-500'
                }`}>
                  {sop.category}
                </span>
                <ChevronRight size={14} className={selectedSop?.id === sop.id ? 'text-blue-200' : 'text-slate-300 group-hover:translate-x-1 transition-transform'} />
              </div>
              <h3 className="font-bold text-base mb-1">{sop.title}</h3>
              <div className="flex items-center gap-2 mt-2">
                <Clock size={12} className={selectedSop?.id === sop.id ? 'text-blue-200' : 'text-slate-400'} />
                <p className={`text-[10px] ${selectedSop?.id === sop.id ? 'text-blue-100' : 'text-slate-400'}`}>
                  Updated {sop.lastUpdated}
                </p>
              </div>
            </button>
          ))}
          {filteredSops.length === 0 && (
            <div className="text-center py-12 bg-slate-50 rounded-3xl border border-dashed border-slate-300">
              <p className="text-slate-500 text-sm italic">No procedures match your search.</p>
            </div>
          )}
        </div>

        {/* SOP Detail */}
        <div className={`lg:col-span-7 print-content ${!selectedSop ? 'hidden lg:block' : 'block'}`}>
          {selectedSop ? (
            <div className="bg-white rounded-3xl border border-slate-100 shadow-lg p-6 lg:p-10 animate-in fade-in zoom-in-95 duration-300 h-fit">
              <button 
                onClick={() => setSelectedSop(null)}
                className="lg:hidden flex items-center gap-2 text-slate-400 mb-6 hover:text-slate-600 no-print"
              >
                <ArrowLeft size={16} />
                <span className="text-sm font-medium">Back to list</span>
              </button>

              <div className="flex items-start gap-4 mb-6">
                <div className="bg-blue-50 p-3 rounded-2xl text-blue-600 no-print hidden sm:block">
                  <Book size={28} />
                </div>
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="bg-blue-100 text-blue-700 text-[10px] font-bold px-2 py-0.5 rounded uppercase">{selectedSop.category}</span>
                    <span className="text-slate-300">•</span>
                    <span className="text-slate-400 text-[10px] font-bold uppercase tracking-widest">{selectedSop.id}</span>
                  </div>
                  <h2 className="text-2xl lg:text-3xl font-bold text-slate-900 leading-tight">{selectedSop.title}</h2>
                </div>
              </div>

              {selectedSop.purpose && (
                <div className="mb-8 p-4 bg-slate-50 border-l-4 border-blue-500 rounded-r-2xl">
                  <p className="text-slate-700 text-sm leading-relaxed">
                    <span className="font-bold text-blue-600 uppercase text-[10px] tracking-widest block mb-1">Purpose</span>
                    {selectedSop.purpose}
                  </p>
                </div>
              )}

              <div className="space-y-8">
                <div>
                  <h4 className="text-[11px] font-bold text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                    <CheckCircle2 size={14} className="text-green-500" />
                    Technical Implementation Steps
                  </h4>
                  <div className="space-y-3">
                    {selectedSop.steps.map((step, i) => (
                      <div key={i} className="flex gap-4 p-4 bg-slate-50 rounded-2xl group border border-transparent hover:border-slate-200 hover:bg-white transition-all">
                        <div className="w-7 h-7 rounded-full bg-white border border-slate-200 flex items-center justify-center font-bold text-slate-400 text-xs shrink-0 group-hover:text-blue-600 group-hover:border-blue-200 transition-colors">
                          {i + 1}
                        </div>
                        <p className="flex-1 text-slate-700 text-sm leading-relaxed pt-0.5">{step}</p>
                      </div>
                    ))}
                  </div>
                </div>

                {selectedSop.escalation && (
                  <div className="p-4 bg-orange-50 border border-orange-100 rounded-2xl flex gap-3">
                    <AlertCircle size={18} className="text-orange-500 shrink-0" />
                    <div>
                      <h5 className="text-[10px] font-bold text-orange-600 uppercase tracking-widest mb-1">Escalation Policy</h5>
                      <p className="text-xs text-orange-800 leading-relaxed font-medium">
                        {selectedSop.escalation}
                      </p>
                    </div>
                  </div>
                )}

                <div className="pt-8 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-500">
                  <div className="flex items-center gap-2">
                    <Hash size={14} className="text-slate-400" />
                    <span>Reference: <span className="font-mono font-bold text-slate-600 tracking-tighter">{selectedSop.id.toUpperCase()}</span></span>
                  </div>
                  <button 
                    onClick={handleExportWord}
                    className="w-full sm:w-auto px-6 py-3 bg-blue-600 text-white rounded-xl font-bold hover:bg-blue-700 transition-all flex items-center justify-center gap-2 no-print shadow-lg shadow-blue-600/20"
                  >
                    <FileText size={16} />
                    Export to Word (.doc)
                  </button>
                </div>
              </div>
            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-center p-12 bg-white rounded-3xl border border-dashed border-slate-200 no-print min-h-[400px]">
              <div className="w-20 h-20 bg-slate-50 rounded-full flex items-center justify-center mb-6">
                <Book size={40} className="text-slate-200" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-2">Knowledge Access</h3>
              <p className="text-slate-500 text-sm max-w-xs leading-relaxed">
                Select a standard operating procedure from the directory on the left to view deployment and troubleshooting steps.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default KnowledgeBase;
